In [1]:
# pip install 'kagglehub[pandas-datasets]'

In [2]:
import kagglehub

# First-time only: authenticates with Kaggle (opens a browser login,
# then caches the token locally so you won't need to do this again).
# kagglehub.login()

/Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/ebenezeryeboah/Library/Python/3.9/lib/python/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
from kagglehub import KaggleDatasetAdapter

# The dataset contains a single file:
file_path = "fifa_world_cup_2026_player_performance.csv"

df = kagglehub.dataset_load(
    KaggleDatasetAdapter.PANDAS,
    "rauffauzanrambe/fifa-world-cup-2026-player-performance-dataset",
    file_path,
)
import pandas as pd

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.2).

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,...,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
0,P00055,Rodri Fati,26,Spanish,Spain,3,Goalkeeper,195,75,Left,...,1.1,44.2,55.9,42.0,51.8,0,0,242,0,5.8
1,P00070,Ansu Le Normand,19,Spanish,Spain,18,Midfielder,178,75,Right,...,3.5,38.2,43.7,31.1,52.7,0,3,342,0,5.5
2,P00066,Gavi Ramos,18,Spanish,Spain,14,Midfielder,177,72,Left,...,15.3,99.0,99.0,83.4,54.8,1,1,245,0,8.4
3,P00073,Pedro Cubarsi,20,Spanish,Spain,21,Forward,182,74,Right,...,1.2,19.8,42.3,40.9,78.5,5,3,422,0,6.7
4,P00059,Alvaro Oyarzabal,23,Spanish,Spain,7,Defender,191,81,Left,...,6.2,44.1,33.5,60.0,56.6,0,0,440,0,5.7

In [4]:
pd.set_option("display.max_columns",None)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  object
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  object
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  object
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  object
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  object
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: float64(18), int64(43), object(14)
memory usage: 31.2+ MB

In [5]:
df.isnull().sum()

player_id                   0
player_name                 0
age                         0
nationality                 0
team                        0
                           ..
total_goals_tournament      0
total_assists_tournament    0
total_minutes_tournament    0
player_of_match_awards      0
tournament_rating           0
Length: 75, dtype: int64

In [6]:
pd.set_option('display.max_columns', None)
df.describe(include='all')

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
count,54600,54600,54600.000000,54600,54600,54600.000000,54600,54600.000000,54600.000000,54600,54600,5.460000e+04,54600,54600,54600,54600,54600,54600,54600,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000,54600.000000
unique,1248,1245,NaN,48,48,NaN,4,NaN,NaN,2,122,NaN,1050,51,16,16,48,7,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,P00960,Pierre-Emile Christensen,NaN,Qatari,Qatar,NaN,Defender,NaN,NaN,Right,Gor Mahia,NaN,M00001,2026-06-30,Lincoln Financial Field,Philadelphia,Qatar,Group Stage,W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,66,86,NaN,1716,1716,NaN,18900,NaN,NaN,40656,892,NaN,52,1560,4264,4264,1716,30056,20124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,26.296484,NaN,NaN,13.500000,NaN,181.654341,75.754853,NaN,NaN,2.008445e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.330476,1.330476,36.199817,0.055385,0.052363,0.447051,0.048425,0.016112,0.017742,0.471832,15.470092,19.177308,0.808440,0.600293,0.162949,0.447784,0.018535,0.802656,0.627271,0.808681,0.226612,0.745256,0.362985,1.388571,2.465220,0.416886,0.323223,0.097912,0.005604,0.086905,0.121282,0.026274,0.026245,0.009176,0.048645,0.003333,3.996504,0.462372,18.645636,10.036502,8.849011,81.893535,3.634700,36.828995,44.716636,52.733712,2.850165,60.318379,46.135778,63.750396,55.572154,0.643993,0.607601,272.300311,0.030659,3.634046
std,NaN,NaN,4.067519,NaN,NaN,7.500069,NaN,6.277792,3.951481,NaN,NaN,2.718866e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.147814,1.147814,36.419755,0.251900,0.239021,0.947155,0.244501,0.074648,0.074896,0.936476,18.747632,22.623857,0.074286,1.154876,0.497236,0.863716,0.137432,1.343731,1.125812,1.534296,0.558672,1.171042,0.713418,2.017851,3.643392,0.771273,0.653396,0.297198,0.074653,0.316943,0.701090,0.135945,0.207966,0.095351,0.330748,0.057639,4.023194,0.475044,16.016266,10.581358,9.390937,10.771734,3.155846,31.072667,24.870780,23.903033,4.228436,20.234988,22.424337,19.860028,13.661343,1.093781,0.931527,116.806184,0.206520,3.163411
min,NaN,NaN,17.000000,NaN,NaN,1.000000,NaN,163.000000,65.000000,NaN,NaN,5.288220e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,50.000000,0.000000,0.000000,1.000000,5.000000,0.000000,15.000000,5.000000,25.000000,15.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,23.000000,NaN,NaN,7.000000,NaN,177.000000,73.000000,NaN,NaN,4.444778e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.760000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,74.600000,0.000000,0.700000,25.675000,33.100000,0.000000,43.700000,29.800000,46.500000,46.400000,0.000000,0.000000,184.000000,0.000000,0.000000
50%,NaN,NaN,26.000000,NaN,NaN,13.500000,NaN,182.000000,76.000000,NaN,NaN,1.027111e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,24.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000,11.000000,0.820000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.300000,29.900000,6.000000,6.000000,82.600000,5.500000,54.100000,41.600000,49.900000,1.100000,57.000000,40.500000,61.100000,55.000000,0.000000,0.000000,268.000000,0.000000,5.400000
75%,NaN,NaN,29.000000,NaN,NaN,20.000000,NaN,186.000000,78.000000,NaN,NaN,2.342013e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,2.000000,75.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,27.000000,33.000000,0.860000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,2.000000,4.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,7.900000,0.900000,32.700000,20.000000,17.000000,90.000000,6.400000,64.100000,60.800000,71.300000,4.000000,75.100000,59.000000,78.900000,63.900000,1.000000,1.000000,359.000000,0.000000,6.400000
max,NaN,NaN,39.000000,NaN,NaN,26.000000,NaN,200.000000,87.000000,NaN,NaN,2.000000e+08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,7.000000,90.000000,4.000000,3.000000,11.000000,5.000000,2.310000,2.200000,8.000000,97.000000,100.000000,0.970000,10.000000,6.000000,8.000000,2.000000,8.000000,7.000000,12.000000,4.000000,7.000000,5.000000,12.000000,23.000000,5.000000,4.000000,1.000000,1.000000,4.000000,11.000000,1.000000,3.000000,1.000000,7.000000,1.000000,14.000000,2.000000,37.000000,44.000000,40.000000,99.000000,9.400000,97.700000,99.000000,99.000000,37.000000,99.000000,99.000000,99.000000,99.000000,10.000000,8.000000,615.000000,4.000000,9.500000

In [7]:
df[df['age']>38]

,player_id,player_name,age,nationality,team,jersey_number,position,height_cm,weight_kg,preferred_foot,club_name,market_value_eur,match_id,match_date,stadium,city,opponent_team,tournament_stage,match_result,goals_team,goals_opponent,minutes_played,goals,assists,shots,shots_on_target,expected_goals_xg,expected_assists_xa,key_passes,successful_passes,total_passes,pass_accuracy,dribbles_attempted,successful_dribbles,crosses,successful_crosses,tackles,interceptions,clearances,blocks,aerial_duels_won,aerial_duels_lost,recoveries,defensive_actions,fouls_committed,fouls_suffered,yellow_cards,red_cards,offsides,saves,save_percentage,punches,clean_sheet,goals_conceded,penalty_saves,distance_covered_km,sprint_distance_km,top_speed_kmh,accelerations,decelerations,stamina_score,player_rating,performance_score,offensive_contribution,defensive_contribution,possession_impact,pressure_resistance,creativity_score,consistency_score,clutch_performance_score,total_goals_tournament,total_assists_tournament,total_minutes_tournament,player_of_match_awards,tournament_rating
882,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00017,2026-07-28,NRG Stadium,Houston,Croatia,Group Stage,D,2,2,0,0,0,0,0,0.0,0.0,0,0,0,0.78,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,73.6,0.0,0.0,8.4,99.0,0.0,97.3,13.5,99.0,54.7,0,0,257,0,0.0
1924,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00038,2026-07-19,Estadio Akron,Guadalajara,Saudi Arabia,Group Stage,L,2,3,68,0,0,0,0,0.0,0.0,0,17,26,0.66,0,0,0,0,0,0,3,0,1,0,3,3,1,1,0,0,0,1,0.89,1,0,3,0,6.7,0.6,30.7,25,15,87.5,6.6,64.0,13.3,99.0,5.4,99.0,16.2,99.0,84.8,0,0,178,0,6.6
2782,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00054,2026-06-23,Gillette Stadium,Boston,Belgium,Group Stage,L,1,2,62,0,0,0,0,0.0,0.0,0,13,20,0.66,0,0,0,0,0,0,1,0,0,0,1,1,0,1,0,0,0,1,0.73,2,0,2,0,6.8,0.9,30.8,14,12,86.7,7.0,70.9,16.7,99.0,3.0,81.7,40.6,99.0,63.5,0,0,415,0,6.8
3066,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00059,2026-06-21,Estadio Akron,Guadalajara,Netherlands,Group Stage,L,0,1,0,0,0,0,0,0.0,0.0,0,0,0,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,81.0,0.0,1.8,17.5,99.0,0.0,73.7,26.2,99.0,50.4,0,0,181,0,0.0
3198,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00062,2026-07-31,BMO Field,Toronto,Peru,Group Stage,L,0,6,76,0,0,0,0,0.0,0.0,0,9,16,0.62,2,0,0,0,0,0,1,0,1,0,4,1,3,0,0,0,0,4,0.80,1,0,6,0,6.2,0.8,30.6,22,20,99.0,6.8,67.8,9.0,99.0,4.6,99.0,15.8,99.0,66.9,0,0,403,0,6.6
3769,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00073,2026-07-23,Levi's Stadium,San Francisco,Poland,Group Stage,L,1,4,0,0,0,0,0,0.0,0.0,0,0,0,0.73,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,63.3,0.0,0.0,10.6,99.0,0.0,91.0,35.1,99.0,35.7,0,0,281,0,0.0
4678,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00090,2026-06-21,BMO Field,Toronto,Morocco,Group Stage,D,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0.82,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,69.8,0.0,0.0,7.0,99.0,0.0,99.0,34.3,99.0,42.5,0,0,54,0,0.0
6578,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00127,2026-07-24,Arrowhead Stadium,Kansas City,Netherlands,Group Stage,W,3,2,77,0,0,0,0,0.0,0.0,0,21,26,0.81,0,0,0,0,0,0,2,0,1,1,2,2,1,0,0,0,0,3,0.69,1,0,2,0,7.2,0.6,27.3,30,11,97.2,6.7,68.7,12.9,99.0,4.8,99.0,26.0,93.0,43.5,0,0,192,0,6.6
6707,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00129,2026-07-11,AT&T Stadium,Dallas,Spain,Group Stage,L,1,2,0,0,0,0,0,0.0,0.0,0,0,0,0.86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,81.5,0.0,0.0,6.6,99.0,0.0,99.0,30.0,99.0,65.0,0,0,417,0,0.0
7227,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00139,2026-07-29,Lincoln Financial Field,Philadelphia,Costa Rica,Group Stage,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,61.9,0.0,0.1,11.6,99.0,0.0,99.0,32.3,99.0,40.2,0,0,96,0,0.0
9724,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00188,2026-06-28,NRG Stadium,Houston,Uruguay,Group Stage,D,1,1,90,0,0,0,0,0.0,0.0,1,10,20,0.52,1,0,0,0,0,0,2,0,1,0,5,2,0,0,0,0,0,2,0.46,2,0,1,0,8.2,1.0,30.4,28,21,87.8,7.4,71.9,8.9,99.0,7.7,99.0,43.7,99.0,53.5,0,0,276,0,7.5
9878,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00190,2026-07-27,Estadio Akron,Guadalajara,Netherlands,Group Stage,L,0,3,0,0,0,0,0,0.0,0.0,0,0,0,0.58,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,77.6,0.0,0.0,10.9,99.0,0.0,99.0,33.7,99.0,64.7,0,0,85,0,0.0
10321,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00199,2026-06-18,Gillette Stadium,Boston,Sweden,Group Stage,L,0,1,0,0,0,0,0,0.0,0.0,0,0,0,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,78.7,0.0,4.5,8.1,99.0,0.0,46.7,39.3,99.0,42.4,0,0,145,0,0.0
11102,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00214,2026-06-18,Estadio Akron,Guadalajara,Netherlands,Group Stage,L,0,1,77,0,0,0,0,0.0,0.0,1,17,26,0.69,1,0,0,0,0,0,2,0,2,0,1,2,0,1,0,0,0,3,0.68,1,0,1,0,7.1,0.9,30.8,26,17,73.1,6.9,68.8,3.8,99.0,6.0,99.0,33.4,99.0,65.0,0,0,254,0,6.9
14117,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00272,2026-07-20,Estadio BBVA,Monterrey,Uruguay,Group Stage,L,0,2,0,0,0,0,0,0.0,0.0,0,0,0,0.74,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,77.0,0.0,4.1,13.5,99.0,0.0,99.0,30.5,99.0,60.0,0,0,325,0,0.0
14663,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00282,2026-07-14,Estadio Akron,Guadalajara,Switzerland,Group Stage,D,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0.62,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,79.9,0.0,3.2,13.6,99.0,0.0,89.3,34.1,99.0,64.5,0,0,37,0,0.0
14922,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00287,2026-07-10,NRG Stadium,Houston,Morocco,Group Stage,D,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0.72,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,76.9,0.0,0.0,7.2,99.0,0.0,99.0,20.4,99.0,53.8,0,0,314,0,0.0
15546,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00299,2026-07-24,Mercedes-Benz Stadium,Atlanta,Senegal,Group Stage,D,1,1,0,0,0,0,0,0.0,0.0,0,0,0,0.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,60.7,0.0,1.8,6.4,99.0,0.0,56.3,36.3,99.0,70.9,0,0,219,0,0.0
17549,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00338,2026-06-19,Estadio Akron,Guadalajara,England,Group Stage,W,2,1,0,0,0,0,0,0.0,0.0,0,0,0,0.69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,59.1,0.0,0.0,12.2,99.0,0.0,69.0,29.3,99.0,65.0,0,0,242,0,0.0
21814,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00420,2026-07-26,BMO Field,Toronto,Spain,Group Stage,L,0,1,73,0,0,0,0,0.0,0.0,1,15,23,0.67,0,0,0,0,0,0,2,0,1,0,1,2,0,2,0,0,0,2,0.86,0,0,1,0,6.1,0.5,28.1,17,19,84.4,6.0,60.1,8.1,99.0,5.1,79.1,26.4,99.0,64.5,0,0,214,0,6.5
22151,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00426,2026-07-27,Mercedes-Benz Stadium,Atlanta,Brazil,Group Stage,W,3,2,0,0,0,0,0,0.0,0.0,0,0,0,0.75,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,82.7,0.0,4.4,1.0,99.0,0.0,99.0,49.2,99.0,55.9,0,0,257,0,0.0
24570,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00473,2026-07-28,MetLife Stadium,East Rutherford,Ecuador,Group Stage,D,0,0,86,0,0,0,0,0.0,0.0,0,17,23,0.78,2,0,0,0,0,1,3,0,4,0,4,4,1,0,0,0,0,3,0.74,1,1,0,0,8.2,1.0,32.7,21,26,99.0,6.9,70.9,8.1,99.0,5.3,78.2,27.4,99.0,78.8,0,0,414,0,6.8
27560,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00531,2026-07-21,NRG Stadium,Houston,Austria,Group Stage,L,0,2,79,0,0,0,0,0.0,0.0,0,15,18,0.87,0,0,0,0,0,0,3,0,2,0,2,3,0,0,0,0,0,2,0.88,0,0,2,1,6.7,0.8,26.0,14,13,99.0,6.5,63.3,14.2,99.0,3.2,99.0,38.8,99.0,57.3,0,0,260,0,6.4
32524,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00626,2026-07-04,Lincoln Financial Field,Philadelphia,Ghana,Round of 32,L,0,2,0,0,0,0,0,0.0,0.0,0,0,0,0.79,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,79.8,0.0,2.2,10.7,99.0,0.0,94.3,36.2,88.6,51.4,0,0,390,0,0.0
33462,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00644,2026-06-11,Gillette Stadium,Boston,United States,Round of 32,W,3,2,73,0,0,0,0,0.0,0.0,0,12,17,0.72,2,0,0,0,0,0,3,0,0,0,2,3,1,0,0,0,0,2,0.71,0,0,2,0,6.9,0.8,29.1,22,20,98.2,7.0,69.3,14.2,99.0,4.0,78.8,42.8,99.0,58.5,0,0,404,0,6.4
35723,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00687,2026-07-04,BC Place,Vancouver,Argentina,Round of 32,W,2,1,0,0,0,0,0,0.0,0.0,0,0,0,0.69,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,50.0,0.0,0.0,8.6,99.0,0.0,99.0,45.7,99.0,63.2,0,0,114,0,0.0
36165,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00696,2026-07-27,BC Place,Vancouver,South Korea,Round of 32,D,2,2,0,0,0,0,0,0.0,0.0,0,0,0,0.71,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,77.4,0.0,0.0,13.1,99.0,0.0,99.0,48.9,99.0,47.8,0,0,262,0,0.0
39102,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00752,2026-06-26,BC Place,Vancouver,Ecuador,Round of 32,L,1,3,0,0,0,0,0,0.0,0.0,0,0,0,0.80,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,64.8,0.0,0.0,8.9,99.0,0.0,95.6,12.1,99.0,49.0,0,0,118,0,0.0
40222,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00774,2026-07-23,Estadio Azteca,Mexico City,Belgium,Round of 16,D,2,2,82,0,0,0,0,0.0,0.0,1,22,31,0.73,0,0,0,0,0,0,2,0,1,0,4,2,3,0,0,0,0,3,0.70,2,0,2,0,8.2,1.2,27.7,21,16,94.3,8.0,81.0,12.4,99.0,7.1,99.0,30.9,99.0,54.7,0,0,400,0,7.8
46486,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00894,2026-06-16,Estadio Akron,Guadalajara,England,Quarter Finals,L,0,1,0,0,0,0,0,0.0,0.0,0,0,0,0.65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,68.1,0.0,1.6,6.8,99.0,0.0,99.0,26.7,74.3,85.7,0,0,281,0,0.0
46928,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00903,2026-07-17,AT&T Stadium,Dallas,Egypt,Quarter Finals,W,1,0,0,0,0,0,0,0.0,0.0,0,0,0,0.77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,74.5,0.0,0.0,17.5,99.0,0.0,99.0,49.7,99.0,88.5,0,0,251,0,0.0
47267,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00909,2026-06-13,BC Place,Vancouver,France,Quarter Finals,L,1,3,0,0,0,0,0,0.0,0.0,0,0,0,0.85,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,72.2,0.0,7.3,8.5,99.0,0.0,99.0,31.0,99.0,96.6,0,0,266,0,0.0
48490,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00933,2026-07-01,Estadio BBVA,Monterrey,Brazil,Quarter Finals,L,2,3,74,0,0,0,0,0.0,0.0,0,11,19,0.63,1,0,1,0,0,1,0,0,0,1,4,1,3,0,0,0,0,3,0.57,3,0,3,0,6.6,0.7,29.4,18,24,95.0,7.5,78.0,6.6,99.0,4.2,88.7,58.0,99.0,99.0,0,0,171,0,7.4
48828,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00940,2026-06-16,Lumen Field,Seattle,Portugal,Quarter Finals,D,1,1,70,0,0,0,0,0.0,0.0,0,18,22,0.82,0,0,0,0,0,0,0,0,1,2,5,0,1,0,0,0,0,3,0.68,0,0,1,0,7.6,0.8,30.2,22,20,99.0,6.4,66.2,10.1,99.0,5.8,99.0,26.6,99.0,99.0,0,0,297,0,6.0
49088,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00945,2026-06-12,Estadio BBVA,Monterrey,Serbia,Quarter Finals,L,1,2,66,0,0,0,0,0.0,0.0,0,11,13,0.86,2,0,0,0,0,1,1,0,1,1,4,2,2,0,0,0,0,4,0.58,0,0,2,0,6.4,0.7,31.4,20,16,83.1,7.4,74.3,1.0,99.0,5.5,74.2,31.6,99.0,99.0,0,0,242,0,7.3
50646,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M00974,2026-07-18,Levi's Stadium,San Francisco,Serbia,Semi Finals,L,0,1,0,0,0,0,0,0.0,0.0,0,0,0,0.77,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,86.6,0.0,0.0,9.0,99.0,0.0,99.0,41.2,99.0,94.2,0,0,388,0,0.0
52025,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M01001,2026-07-27,MetLife Stadium,East Rutherford,Belgium,Semi Finals,D,2,2,0,0,0,0,0,0.0,0.0,0,0,0,0.81,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,71.5,0.0,5.1,6.9,99.0,0.0,99.0,14.6,99.0,57.8,0,0,264,0,0.0
54416,P00419,Mykhailo Sudakov,39,Ukrainian,Ukraine,3,Goalkeeper,185,82,Right,Anderlecht,82306689,M01047,2026-07-22,BC Place,Vancouver,United States,Final,L,0,5,0,0,0,0,0,0.0,0.0,0,0,0,0.63,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0.00,0,0,0,0,0.0,0.0,0.0,0,0,73.2,0.0,0.1,7.3,99.0,0.0,54.6,33.7,99.0,99.0,0,0,105,0,0.0

In [8]:
df['player_id'].nunique()

1248

In [9]:
df.shape

(54600, 75)

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.groupby('team')['player_name']

In [12]:
df.duplicated(subset=['player_id', 'match_id']).sum()

np.int64(0)

In [13]:
df.duplicated(subset=['player_id', 'match_id']).sum()

#Helps to know duplicates bases on player id and match id

np.int64(0)

In [14]:
df.select_dtypes(include=['object']).nunique()

player_id           1248
player_name         1245
nationality           48
team                  48
position               4
preferred_foot         2
club_name            122
match_id            1050
match_date            51
stadium               16
city                  16
opponent_team         48
tournament_stage       7
match_result           3
dtype: int64

In [15]:
df.match_date.dtype

dtype('O')

In [16]:
df['match_date']= pd.to_datetime(df['match_date'])

In [17]:
df.match_date.dtype

dtype('<M8[ns]')

In [18]:
mem_before = df.memory_usage(deep=True).sum()

In [19]:
df.dtypes

player_id                    object
player_name                  object
age                           int64
nationality                  object
team                         object
                             ...
total_goals_tournament        int64
total_assists_tournament      int64
total_minutes_tournament      int64
player_of_match_awards        int64
tournament_rating           float64
Length: 75, dtype: object

In [20]:
df.columns
cat = df[['team', 'position','preferred_foot','match_result']]

In [21]:
for c in cat:
    df[c]=df[c].astype('category')

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54600 entries, 0 to 54599
Data columns (total 75 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   player_id                 54600 non-null  object
 1   player_name               54600 non-null  object
 2   age                       54600 non-null  int64
 3   nationality               54600 non-null  object
 4   team                      54600 non-null  category
 5   jersey_number             54600 non-null  int64
 6   position                  54600 non-null  category
 7   height_cm                 54600 non-null  int64
 8   weight_kg                 54600 non-null  int64
 9   preferred_foot            54600 non-null  category
 10  club_name                 54600 non-null  object
 11  market_value_eur          54600 non-null  int64
 12  match_id                  54600 non-null  object
 13  match_date                54600 non-null  datetime64[ns]
 14  stadium                   54600 non-null  object
 15  city                      54600 non-null  object
 16  opponent_team             54600 non-null  object
 17  tournament_stage          54600 non-null  object
 18  match_result              54600 non-null  category
 19  goals_team                54600 non-null  int64
 20  goals_opponent            54600 non-null  int64
 21  minutes_played            54600 non-null  int64
 22  goals                     54600 non-null  int64
 23  assists                   54600 non-null  int64
 24  shots                     54600 non-null  int64
 25  shots_on_target           54600 non-null  int64
 26  expected_goals_xg         54600 non-null  float64
 27  expected_assists_xa       54600 non-null  float64
 28  key_passes                54600 non-null  int64
 29  successful_passes         54600 non-null  int64
 30  total_passes              54600 non-null  int64
 31  pass_accuracy             54600 non-null  float64
 32  dribbles_attempted        54600 non-null  int64
 33  successful_dribbles       54600 non-null  int64
 34  crosses                   54600 non-null  int64
 35  successful_crosses        54600 non-null  int64
 36  tackles                   54600 non-null  int64
 37  interceptions             54600 non-null  int64
 38  clearances                54600 non-null  int64
 39  blocks                    54600 non-null  int64
 40  aerial_duels_won          54600 non-null  int64
 41  aerial_duels_lost         54600 non-null  int64
 42  recoveries                54600 non-null  int64
 43  defensive_actions         54600 non-null  int64
 44  fouls_committed           54600 non-null  int64
 45  fouls_suffered            54600 non-null  int64
 46  yellow_cards              54600 non-null  int64
 47  red_cards                 54600 non-null  int64
 48  offsides                  54600 non-null  int64
 49  saves                     54600 non-null  int64
 50  save_percentage           54600 non-null  float64
 51  punches                   54600 non-null  int64
 52  clean_sheet               54600 non-null  int64
 53  goals_conceded            54600 non-null  int64
 54  penalty_saves             54600 non-null  int64
 55  distance_covered_km       54600 non-null  float64
 56  sprint_distance_km        54600 non-null  float64
 57  top_speed_kmh             54600 non-null  float64
 58  accelerations             54600 non-null  int64
 59  decelerations             54600 non-null  int64
 60  stamina_score             54600 non-null  float64
 61  player_rating             54600 non-null  float64
 62  performance_score         54600 non-null  float64
 63  offensive_contribution    54600 non-null  float64
 64  defensive_contribution    54600 non-null  float64
 65  possession_impact         54600 non-null  float64
 66  pressure_resistance       54600 non-null  float64
 67  creativity_score          54600 non-null  float64
 68  consistency_score         54600 non-null  float64
 69  clutch_performance_score  54600 non-null  float64
 70  total_goals_tournament    54600 non-null  int64
 71  total_assists_tournament  54600 non-null  int64
 72  total_minutes_tournament  54600 non-null  int64
 73  player_of_match_awards    54600 non-null  int64
 74  tournament_rating         54600 non-null  float64
dtypes: category(4), datetime64[ns](1), float64(18), int64(43), object(9)
memory usage: 29.8+ MB

In [23]:
df.dtypes

player_id                     object
player_name                   object
age                            int64
nationality                   object
team                        category
                              ...
total_goals_tournament         int64
total_assists_tournament       int64
total_minutes_tournament       int64
player_of_match_awards         int64
tournament_rating            float64
Length: 75, dtype: object

In [29]:
df['tournament_stage'].sort_values().unique()

array(['Final', 'Group Stage', 'Quarter Finals', 'Round of 16',
       'Round of 32', 'Semi Finals', 'Third Place Match'], dtype=object)

In [24]:
mem_after = df.memory_usage(deep=True).sum()

In [25]:
df['tournament_stage'].unique()

array(['Group Stage', 'Round of 32', 'Round of 16', 'Quarter Finals',
       'Semi Finals', 'Third Place Match', 'Final'], dtype=object)

In [26]:
print(mem_before, mem_after)

73441567 60040835

In [30]:
stage_order = ['Group Stage', 'Round of 32', 'Round of 16', 'Quarter Finals', 'Semi Finals', 'Third Place Match', 'Final']
df['tournament_stage'] = pd.Categorical(df['tournament_stage'], categories=stage_order, ordered = True)

In [32]:
df.tournament_stage.sort_values().unique()

['Group Stage', 'Round of 32', 'Round of 16', 'Quarter Finals', 'Semi Finals', 'Third Place Match', 'Final']
Categories (7, object): ['Group Stage' < 'Round of 32' < 'Round of 16' < 'Quarter Finals' < 'Semi Finals' < 'Third Place Match' < 'Final']