In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../Data/data.csv')
df.head()

   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [5]:
df.shape

(169, 4)

In [6]:
df.shape[0]

169

In [8]:
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [13]:
df.columns

Index(['Duration', 'Pulse', 'Maxpulse', 'Calories'], dtype='object')

In [10]:
df['Duration'].min()

np.int64(15)

In [11]:
df.Pulse.max()

np.int64(159)

In [ ]:
df[df.columns[1]].mean() #mode,median

np.float64(107.46153846153847)

In [35]:
df[df.duplicated()]

     Duration  Pulse  Maxpulse  Calories
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
40         45     90       112     180.1
71         60    109       153     387.6
113        45    100       120     225.3
155        60    111       151     368.5

In [43]:
df.groupby('Pulse')['Duration'].mean()

Pulse
80      22.500000
83      20.000000
85      30.000000
90      80.000000
92      50.000000
93      60.000000
95      31.666667
97      83.571429
98      65.000000
99      75.000000
100     77.368421
101    120.000000
102     57.500000
103     53.333333
104     52.500000
105     70.000000
106     50.833333
107     67.500000
108    113.571429
109     62.777778
110     66.428571
111     57.500000
112     45.000000
113     45.000000
114     56.250000
115     50.000000
116     60.000000
117     50.000000
118     55.000000
119     60.000000
120     75.000000
121     60.000000
122     45.000000
123     62.500000
124     15.000000
125     75.000000
129     45.000000
130     60.000000
136     36.666667
137    210.000000
141     20.000000
149     45.000000
150     25.000000
151     25.000000
152     25.000000
153     20.000000
159     30.000000
Name: Duration, dtype: float64

In [51]:
df[df.Pulse==150 & 120]

Empty DataFrame
Columns: [Duration, Pulse, Maxpulse, Calories]
Index: []

In [54]:
df[['Pulse','Maxpulse','Calories']].corr()

             Pulse  Maxpulse  Calories
Pulse     1.000000  0.786535  0.025121
Maxpulse  0.786535  1.000000  0.203813
Calories  0.025121  0.203813  1.000000

In [57]:
df.sort_values( by='Pulse', ascending=False)

     Duration  Pulse  Maxpulse  Calories
80         30    159       182     319.2
58         20    153       172     226.4
97         25    152       168     244.2
85         30    151       170     300.0
95         20    151       168     229.4
..        ...    ...       ...       ...
106       180     90       120     800.3
160        30     85       120     250.4
89         20     83       107      50.3
93         15     80       100      50.5
159        30     80       120     240.9

[169 rows x 4 columns]

In [64]:
df['Rank'] = df['Pulse'].rank(ascending=True, method ='first')
df

     Duration  Pulse  Maxpulse  Calories   Rank
0          60    110       130     409.1  117.0
1          60    117       145     479.0  141.0
2          60    103       135     340.0   68.0
3          45    109       175     282.4  108.0
4          45    117       148     406.0  142.0
..        ...    ...       ...       ...    ...
164        60    105       140     290.8   86.0
165        60    110       145     300.0  123.0
166        60    115       145     310.2  139.0
167        75    120       150     320.4  148.0
168        75    125       150     330.4  154.0

[169 rows x 5 columns]

In [65]:
df.sort_values(by='Rank')

     Duration  Pulse  Maxpulse  Calories   Rank
93         15     80       100      50.5    1.0
159        30     80       120     240.9    2.0
89         20     83       107      50.3    3.0
160        30     85       120     250.4    4.0
17         45     90       112       NaN    5.0
..        ...    ...       ...       ...    ...
85         30    151       170     300.0  165.0
95         20    151       168     229.4  166.0
97         25    152       168     244.2  167.0
58         20    153       172     226.4  168.0
80         30    159       182     319.2  169.0

[169 rows x 5 columns]

### Cleaning Data

In [1]:
import pandas as pd
import numpy as np

data = {
    "Name": [" Ama ", "Kojo", "Yaw", "Ama", None],
    "Age": [22, np.nan, 25, 22, 30],
    "Gender": ["F", "M", "m", "F", "Male"],
    "Salary": [3000, 5000, None, 3000, 6000],
    "Department": ["HR", "IT", "IT", "HR", " Finance "]
}

df = pd.DataFrame(data)

In [2]:
df.head()

    Name   Age Gender  Salary Department
0   Ama   22.0      F  3000.0         HR
1   Kojo   NaN      M  5000.0         IT
2    Yaw  25.0      m     NaN         IT
3    Ama  22.0      F  3000.0         HR
4   None  30.0   Male  6000.0   Finance

In [3]:
df.isnull().sum()
df['Department'].value_counts()

Department
HR           2
IT           2
 Finance     1
Name: count, dtype: int64

In [96]:
(df.isnull().sum())/df.isnull().sum().sum() *100

Name          33.333333
Age           33.333333
Gender         0.000000
Salary        33.333333
Department     0.000000
dtype: float64

In [97]:
df.isnull().sum().sum()

np.int64(3)

In [98]:
df.dropna()

    Name   Age Gender  Salary Department
0   Ama   22.0      F  3000.0         HR
3    Ama  22.0      F  3000.0         HR

In [99]:
df

    Name   Age Gender  Salary Department
0   Ama   22.0      F  3000.0         HR
1   Kojo   NaN      M  5000.0         IT
2    Yaw  25.0      m     NaN         IT
3    Ama  22.0      F  3000.0         HR
4   None  30.0   Male  6000.0   Finance

In [100]:
df.dropna(axis=1)

  Gender Department
0      F         HR
1      M         IT
2      m         IT
3      F         HR
4   Male   Finance

In [101]:
df.dropna(subset=['Salary'])

    Name   Age Gender  Salary Department
0   Ama   22.0      F  3000.0         HR
1   Kojo   NaN      M  5000.0         IT
3    Ama  22.0      F  3000.0         HR
4   None  30.0   Male  6000.0   Finance

In [109]:
# df.fillna(value = )

In [103]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [108]:
df.duplicated().sum()

np.int64(0)

In [107]:
df.drop_duplicates()

    Name    Age Gender  Salary Department
0   Ama   22.00      F  3000.0         HR
1   Kojo  24.75      M  5000.0         IT
2    Yaw  25.00      m     NaN         IT
3    Ama  22.00      F  3000.0         HR
4   None  30.00   Male  6000.0   Finance

In [111]:
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [112]:
df

    Name    Age Gender  Salary Department
0   Ama   22.00      F  3000.0         HR
1   Kojo  24.75      M  5000.0         IT
2    Yaw  25.00      m  4250.0         IT
3    Ama  22.00      F  3000.0         HR
4   None  30.00   Male  6000.0   Finance

In [113]:
df['Name'] = df["Name"].str.strip()

In [114]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         HR
1  Kojo  24.75      M  5000.0         IT
2   Yaw  25.00      m  4250.0         IT
3   Ama  22.00      F  3000.0         HR
4  None  30.00   Male  6000.0   Finance

In [117]:
df.Gender = df.Gender.str.upper()

In [118]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         HR
1  Kojo  24.75      M  5000.0         IT
2   Yaw  25.00      M  4250.0         IT
3   Ama  22.00      F  3000.0         HR
4  None  30.00   MALE  6000.0   Finance

In [119]:
df['Gender'] = df['Gender'].replace({
    'male':'M',
    'Female':'F',
    'MALE':'M'
})

In [120]:
DF

NameError: name 'DF' is not defined

In [121]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         HR
1  Kojo  24.75      M  5000.0         IT
2   Yaw  25.00      M  4250.0         IT
3   Ama  22.00      F  3000.0         HR
4  None  30.00      M  6000.0   Finance

In [122]:
df["Department"] = (
    df["Department"].str.title()
)

In [123]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         Hr
1  Kojo  24.75      M  5000.0         It
2   Yaw  25.00      M  4250.0         It
3   Ama  22.00      F  3000.0         Hr
4  None  30.00      M  6000.0   Finance

In [124]:
df.rename(columns={
    'Gender':'Sex'
})

   Name    Age Sex  Salary Department
0   Ama  22.00   F  3000.0         Hr
1  Kojo  24.75   M  5000.0         It
2   Yaw  25.00   M  4250.0         It
3   Ama  22.00   F  3000.0         Hr
4  None  30.00   M  6000.0   Finance

In [134]:
df.Department = df.Department.str.strip()
df.Department = df['Department'].replace({
    'Finance':'F'
})

In [135]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         Hr
1  Kojo  24.75      M  5000.0         It
2   Yaw  25.00      M  4250.0         It
3   Ama  22.00      F  3000.0         Hr
4  None  30.00      M  6000.0          F

In [136]:
# Option 1 — simplest
df['Department'] = df['Department'].replace('Finance', 'F')

# Option 2 — loc approach
df.loc[df['Department'] == 'Finance', 'Department'] = 'F'

In [137]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         Hr
1  Kojo  24.75      M  5000.0         It
2   Yaw  25.00      M  4250.0         It
3   Ama  22.00      F  3000.0         Hr
4  None  30.00      M  6000.0          F

In [138]:
df.Department = df.Department.str.upper()

In [139]:
df

   Name    Age Gender  Salary Department
0   Ama  22.00      F  3000.0         HR
1  Kojo  24.75      M  5000.0         IT
2   Yaw  25.00      M  4250.0         IT
3   Ama  22.00      F  3000.0         HR
4  None  30.00      M  6000.0          F